// Shared logic for the examples-consistency tooling.
//
// The sample repos under examples/* each carry a copy of the
// `site-content-sync` skill. The single source of truth is the canonical tree
// at examples/_shared/site-content-sync/; the copies (skills/site-content-sync/
// and .github/workflows/sync-*.yml) are sync output generated by
// scripts/sync-examples.mjs and verified by scripts/check-examples.mjs.
//
// This module holds everything the two scripts must agree on: paths, the
// per-example workflow set, and file-walking helpers. Keeping it shared means
// the generator and the drift guard can never disagree about what an example
// should contain.

import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs';
import { join, relative, sep } from 'node:path';

export const ROOT = process.cwd();
export const EXAMPLES_DIR = join(ROOT, 'examples');
export const SHARED_SKILL_DIR = join(EXAMPLES_DIR, '_shared', 'site-content-sync');

/**
 * Per-example sync workflow set (owner decision 2: each example carries one
 * workflow matching its content type): each example carries exactly the
 * workflows matching its content type, generated from the canonical templates
 * under examples/_shared/site-content-sync/templates/.
 *
 *   - my-posts (posts only)            -> sync-posts.yml, no PRODUCT
 *   - vite-docs / astro-docs /
 *     json-server-docs (docs + landing) -> sync-docs.yml, PRODUCT set
 *
 * To add a new example: create its repo dir under examples/ and add an entry
 * here. `npm run sync:examples` then generates its skill copy + workflows, and
 * `npm run check:examples` verifies them.
 */
export const EXAMPLE_WORKFLOWS = {
  'my-posts': [{ template: 'sync-posts.yml', product: null }],
  'vite-docs': [{ template: 'sync-docs.yml', product: 'vite' }],
  'astro-docs': [{ template: 'sync-docs.yml', product: 'astro' }],
  'json-server-docs': [{ template: 'sync-docs.yml', product: 'json-server' }],
};

/** Discover example dirs: every non-hidden subdir of examples/ except the
 *  `_shared` canonical tree. Deliberately content-agnostic so a missing skill
 *  copy is reported as drift rather than silently skipping the example. */
export function listExamples() {
  if (!existsSync(EXAMPLES_DIR)) return [];
  return readdirSync(EXAMPLES_DIR)
    .filter((name) => !name.startsWith('.') && name !== '_shared')
    .filter((name) => statSync(join(EXAMPLES_DIR, name)).isDirectory())
    .sort();
}

/** Recursively list all files under `dir` as relative POSIX paths (sorted). */
export function walkFiles(dir, root = dir) {
  if (!existsSync(dir)) return [];
  const out = [];
  for (const name of readdirSync(dir)) {
    const abs = join(dir, name);
    if (statSync(abs).isDirectory()) {
      out.push(...walkFiles(abs, root));
    } else {
      out.push(relative(root, abs).split(sep).join('/'));
    }
  }
  return out.sort();
}

/**
 * Render the .github/workflows file an example should carry, from the
 * canonical template. Returns { name, content } where `name` is the workflow
 * filename (e.g. 'sync-docs.yml'). The <HUB_REPO> / <HUB_TOKEN_SECRET>
 * placeholders are kept as-is (deployment-specific, filled in by the example
 * owner); only PRODUCT is substituted per example.
 */
export function renderWorkflow(spec) {
  const template = join(SHARED_SKILL_DIR, 'templates', spec.template);
  let content = readFileSync(template, 'utf8');
  if (spec.product) {
    content = content.replace('PRODUCT: <PRODUCT>', `PRODUCT: ${spec.product}`);
  }
  return { name: spec.template, content };
}
